# Generated by Django 2.2.17 on 2020-11-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20201123_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststring',
            name='string',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
